name: Build & Deploy

on:
  - push

jobs:
  build-deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Switch node version
        shell: bash -l {0}
        run: nvm install
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Deploy
        run: |
          if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
            npm run deploy -- --prod
          else
            npm run deploy
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
